### Python异常机制

错误：语法错误又称解析错误
异常：打破程序正常执行流程的一些事件
区别：语句或表达式在语法上是正确的，但在尝试执行时，它仍可能会引发错误。 在执行时检测到的错误被称为异常

BaseException
    基类异常，Python中所有异常都继承它
Exception
    除非系统退出类异常的其他异常的基类，我们自定义的异常继承它。

**Python层次**
```python
BaseException
 +-- SystemExit     # 解释器请求退出
 +-- KeyboardInterrupt  # 用户中断执行(通常是输入^C)
 +-- GeneratorExit  # 生成器(generator)发生异常来通知退出
 +-- Exception      # 常规错误的基类
      +-- StopIteration
      +-- StopAsyncIteration
      +-- ArithmeticError
      |    +-- FloatingPointError
      |    +-- OverflowError
      |    +-- ZeroDivisionError
      +-- AssertionError
      +-- AttributeError
      +-- BufferError
      +-- EOFError
      +-- ImportError
      |    +-- ModuleNotFoundError
      +-- LookupError
      |    +-- IndexError
      |    +-- KeyError
      +-- MemoryError
      +-- NameError
      |    +-- UnboundLocalError
      +-- OSError
      |    +-- BlockingIOError
      |    +-- ChildProcessError
      ......
```

#### 1.异常处理

When ？什么时候要捕获异常？
```python
网络请求（超时，链接错误等）
资源访问（权限问题，资源不存在等）
代码逻辑（越界，keyError等）

```

How ？怎么处理异常？
```python
try:
    # 可能发生异常的代码
except 异常种类(一个或多个) as e:
    # 异常处理
else:
    # 没有异常时的操作
finally:
    # 不论有没有异常都会执行的代码

```

#### 2.自定义异常
异常通常应该直接或间接地从 Exception 类派生。大多数异常都定义为名称以“Error”结尾，类似于标准异常的命名。

示例：
```python
class Error(Exception):
    """Base class for exceptions in this module."""
    pass

class InputError(Error):
    """Exception raised for errors in the input.

    Attributes:
        expression -- input expression in which the error occurred
        message -- explanation of the error
    """

    def __init__(self, expression, message):
        self.expression = expression
        self.message = message

class TransitionError(Error):
    """Raised when an operation attempts a state transition that's not
    allowed.

    Attributes:
        previous -- state at beginning of transition
        next -- attempted new state
        message -- explanation of why the specific transition is not allowed
    """

    def __init__(self, previous, next, message):
        self.previous = previous
        self.next = next
        self.message = message

```

抛出自定义的异常：raise

**自定义为什么通常不继承 BaseException ?**
    如果继承BaseException，在捕获多个自定义异常时，通常在except处写他们的父类，这样的话，就会把其他系统推出类异常捕获到进行处理。
    如 ctrl c 中断程序这个异常被捕获，是我们在想要中断程序运行时按 ctrl c 失效。
    我们继承Exception，就可以直接捕获到Exception下所有子类异常包括我们自定义的异常。





















